# Generated by Django 3.2.7 on 2021-11-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0006_remove_user_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
