# Generated by Django 3.2.7 on 2021-11-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0007_user_is_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='telemedicine_user',
        ),
    ]
