# Generated by Django 3.2.7 on 2021-12-04 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0010_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chartreports',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 19, 49, 57, 200344)),
        ),
        migrations.AlterField(
            model_name='chartreports',
            name='fileurl',
            field=models.FileField(upload_to='documents/patientreports'),
        ),
        migrations.AlterField(
            model_name='chartreports',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='chartreports',
            name='patientno',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients'),
        ),
    ]
