# Generated by Django 3.2.7 on 2021-12-04 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0017_auto_20211203_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartreports',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 20, 1, 21, 646154)),
        ),
        migrations.AlterField(
            model_name='patients',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
