# Generated by Django 3.2.7 on 2021-12-05 05:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0020_auto_20211203_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patientno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chartreports',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 5, 0, 36, 13, 425672)),
        ),
    ]
